management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zipkin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia%2FShanghai
    username: root
    password: root
    product:
      url: jdbc:mysql://localhost:3306/products?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia%2FShanghai
      username: root
      password: root
    order:
      url: jdbc:mysql://localhost:3306/orders?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia%2FShanghai
      username: root
      password: root
  rabbitmq:
    addresses: 172.17.0.2:5672
    username: admin
    password: admin
  redis:
    host: 172.17.0.2
    port: 6379
  thymeleaf:
    cache: false

